package com.thenewkenya.ingrediet.feature.mealplanner

import android.content.Intent
import android.widget.Toast
import androidx.compose.animation.AnimatedVisibility
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.foundation.text.KeyboardOptions
import androidx.lifecycle.viewmodel.compose.viewModel
import androidx.navigation.NavController
import coil3.compose.AsyncImage
import java.time.DayOfWeek
import java.time.LocalDate
import java.time.format.DateTimeFormatter
import java.time.format.TextStyle
import java.time.temporal.ChronoUnit
import java.util.Locale

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun MealPlannerScreen(
    navController: NavController,
    viewModel: MealPlannerViewModel = viewModel(
        factory = MealPlannerViewModelFactory(LocalContext.current)
    )
) {
    val colors = MaterialTheme.colorScheme
    val typography = MaterialTheme.typography
    val context = LocalContext.current
    
    // Collect state values from the ViewModel
    val currentWeek by viewModel.currentWeek.collectAsState()
    val mealPlans by viewModel.mealPlans.collectAsState()
    val dailyNutrition by viewModel.dailyNutrition.collectAsState()
    val isLoading by viewModel.isLoading.collectAsState()
    val isGenerating by viewModel.isGenerating.collectAsState()
    val error by viewModel.error.collectAsState()
    val generationProgress by viewModel.generationProgress.collectAsState()
    val generationStage by viewModel.generationStage.collectAsState()
    
    // Generate dates for the weekly calendar
    val selectedDate = remember { mutableStateOf(LocalDate.now()) }
    val selectedDateValue by selectedDate
    
    val startOfWeek = remember(selectedDateValue) {
        selectedDateValue.with(DayOfWeek.MONDAY)
    }
    
    val calendarDates = remember(startOfWeek) {
        (0..6).map { startOfWeek.plusDays(it.toLong()) }
    }
    
    // Dialog state
    var showAutoGenerateDialog by remember { mutableStateOf(false) }
    var showAddMealDialog by remember { mutableStateOf(false) }
    var showNutritionDialog by remember { mutableStateOf(false) }
    var showShareDialog by remember { mutableStateOf(false) }
    
    // For navigation between weeks
    fun navigateToWeek(direction: Int) {
        selectedDate.value = selectedDateValue.plusWeeks(direction.toLong())
    }
    
    // Function to share meal plan
    fun shareMealPlan() {
        val (text, fileName) = viewModel.shareMealPlan()
        
        val sendIntent = Intent().apply {
            action = Intent.ACTION_SEND
            putExtra(Intent.EXTRA_TEXT, text)
            putExtra(Intent.EXTRA_TITLE, "My Meal Plan")
            type = "text/plain"
        }
        
        val shareIntent = Intent.createChooser(sendIntent, null)
        context.startActivity(shareIntent)
    }
    
    // Function to save meal plan
    fun saveMealPlan() {
        val text = viewModel.generateMealPlanSummary()
        viewModel.saveMealPlanToFile(text).onSuccess { filePath ->
            Toast.makeText(context, "Meal plan saved to $filePath", Toast.LENGTH_LONG).show()
        }.onFailure { error ->
            Toast.makeText(context, "Failed to save: ${error.message}", Toast.LENGTH_SHORT).show()
        }
    }
    
    Scaffold(
        containerColor = colors.background,
        topBar = {
            TopAppBar(
                title = { 
                    Row(
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Text(
                            text = "Meal Planner",
                            style = typography.titleLarge.copy(fontWeight = FontWeight.Bold)
                        )
                        Spacer(modifier = Modifier.width(8.dp))
                        // Week navigation
                        IconButton(
                            onClick = { navigateToWeek(-1) }, // Previous week
                            modifier = Modifier.size(24.dp)
                        ) {
                            Icon(
                                imageVector = Icons.Default.KeyboardArrowLeft,
                                contentDescription = "Previous week",
                                tint = colors.onBackground
                            )
                        }
                        Text(
                            text = currentWeek,
                            style = typography.bodyMedium
                        )
                        IconButton(
                            onClick = { navigateToWeek(1) }, // Next week
                            modifier = Modifier.size(24.dp)
                        ) {
                            Icon(
                                imageVector = Icons.Default.KeyboardArrowRight,
                                contentDescription = "Next week",
                                tint = colors.onBackground
                            )
                        }
                    }
                },
                navigationIcon = {
                    IconButton(onClick = { navController.navigateUp() }) {
                        Icon(
                            imageVector = Icons.AutoMirrored.Filled.ArrowBack,
                            contentDescription = "Back",
                            tint = colors.onBackground
                        )
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = colors.background,
                    titleContentColor = colors.onBackground
                ),
                actions = {
                    // Share button
                    IconButton(onClick = { showShareDialog = true }) {
                        Icon(
                            imageVector = Icons.Default.Share,
                            contentDescription = "Share meal plan",
                            tint = colors.onBackground
                        )
                    }
                    // Nutrition summary button
                    IconButton(onClick = { showNutritionDialog = true }) {
                        Icon(
                            imageVector = Icons.Default.BarChart,
                            contentDescription = "Nutrition summary",
                            tint = colors.onBackground
                        )
                    }
                    // Auto-generate meal plan button
                    IconButton(onClick = { showAutoGenerateDialog = true }) {
                        Icon(
                            imageVector = Icons.Default.AutoAwesome,
                            contentDescription = "Auto-generate meal plan",
                            tint = colors.onBackground
                        )
                    }
                }
            )
        },
        floatingActionButton = {
            FloatingActionButton(
                onClick = { showAddMealDialog = true },
                containerColor = colors.primary,
                contentColor = colors.onPrimary
            ) {
                Icon(Icons.Default.Add, contentDescription = "Add Meal")
            }
        }
    ) { paddingValues ->
        Box(
            modifier = Modifier
                .fillMaxSize()
                .padding(paddingValues)
                .background(colors.background)
        ) {
            Column(
                modifier = Modifier.fillMaxSize()
            ) {
                // Weekly calendar
                CalendarView(
                    dates = calendarDates,
                    selectedDate = selectedDateValue,
                    onDateSelected = { selectedDate.value = it }
                )
                
                // Show content based on state
                when {
                    isLoading || isGenerating -> {
                        Box(
                            contentAlignment = Alignment.Center,
                            modifier = Modifier
                                .fillMaxSize()
                                .padding(16.dp)
                        ) {
                            Column(
                                horizontalAlignment = Alignment.CenterHorizontally,
                                verticalArrangement = Arrangement.spacedBy(16.dp)
                            ) {
                                if (isGenerating) {
                                    // Show generation progress with a linear progress indicator
                                    Column(
                                        horizontalAlignment = Alignment.CenterHorizontally,
                                        verticalArrangement = Arrangement.spacedBy(8.dp),
                                        modifier = Modifier
                                            .padding(horizontal = 32.dp)
                                            .fillMaxWidth()
                                    ) {
                                        LinearProgressIndicator(
                                            progress = { generationProgress },
                                            modifier = Modifier.fillMaxWidth(),
                                            color = colors.primary,
                                            trackColor = colors.primaryContainer
                                        )
                                        
                                        Text(
                                            text = generationStage ?: "Generating your meal plan...",
                                            style = typography.bodyMedium,
                                            color = colors.onBackground,
                                            textAlign = TextAlign.Center
                                        )
                                        
                                        Text(
                                            text = "${(generationProgress * 100).toInt()}%",
                                            style = typography.labelMedium,
                                            color = colors.primary,
                                            textAlign = TextAlign.Center,
                                            modifier = Modifier.padding(top = 4.dp)
                                        )
                                    }
                                } else {
                                    // Regular loading indicator
                                    CircularProgressIndicator(color = colors.primary)
                                    Text(
                                        text = "Loading...",
                                        style = typography.bodyLarge,
                                        color = colors.onBackground
                                    )
                                }
                            }
                        }
                    }
                    
                    error != null -> {
                        Box(
                            contentAlignment = Alignment.Center,
                            modifier = Modifier
                                .fillMaxSize()
                                .padding(16.dp)
                        ) {
                            Column(
                                horizontalAlignment = Alignment.CenterHorizontally,
                                verticalArrangement = Arrangement.spacedBy(16.dp)
                            ) {
                                Icon(
                                    imageVector = Icons.Default.Error,
                                    contentDescription = null,
                                    tint = colors.error,
                                    modifier = Modifier.size(48.dp)
                                )
                                Text(
                                    text = error ?: "An unexpected error occurred",
                                    style = typography.bodyLarge,
                                    color = colors.error,
                                    textAlign = TextAlign.Center
                                )
                                Button(
                                    onClick = { /* Retry loading */ },
                                    colors = ButtonDefaults.buttonColors(
                                        containerColor = colors.primary
                                    )
                                ) {
                                    Text("Retry")
                                }
                            }
                        }
                    }
                    
                    else -> {
                        // Daily meal plan
                        DailyMealPlan(
                            date = selectedDateValue,
                            meals = viewModel.getMealsForDay(selectedDateValue.dayOfWeek),
                            onDeleteMeal = { viewModel.removeMeal(it) },
                            onAddMeal = { mealTime, name, description, calories, recipeId ->
                                val meal = MealPlanItem(
                                    id = "${selectedDateValue.dayOfWeek}_${mealTime}_${System.currentTimeMillis()}",
                                    name = mealTime,
                                    calories = calories,
                                    day = selectedDateValue.dayOfWeek,
                                    time = when(mealTime) {
                                        "Breakfast" -> MealTime.Breakfast
                                        "Lunch" -> MealTime.Lunch
                                        "Dinner" -> MealTime.Dinner
                                        else -> MealTime.Snacks
                                    },
                                    description = description.ifEmpty { name },
                                    recipeId = recipeId,
                                    imageUrl = recipeId?.let { "https://source.unsplash.com/random/300x200?food" }
                                )
                                viewModel.addMeal(meal)
                            },
                            colors = colors,
                            typography = typography,
                            onRecipeClick = { recipeId -> 
                                if (recipeId != null) {
                                    navController.navigate("recipe/$recipeId")
                                }
                            }
                        )
                    }
                }
            }
        }
    }
    
    // Auto-generate meal plan dialog
    if (showAutoGenerateDialog) {
        AutoGenerateMealPlanDialog(
            onDismiss = { showAutoGenerateDialog = false },
            onGenerate = { calories, dietType, allergies -> 
                viewModel.generateMealPlan(calories, dietType, allergies)
                showAutoGenerateDialog = false 
            }
        )
    }
    
    // Add custom meal dialog (for FAB)
    if (showAddMealDialog) {
        AddCustomMealTimeDialog(
            onDismiss = { showAddMealDialog = false },
            onSelectMealTime = { mealTime, name, description, calories, recipeId ->
                val meal = MealPlanItem(
                    id = "${selectedDateValue.dayOfWeek}_${mealTime}_${System.currentTimeMillis()}",
                    name = mealTime,
                    calories = calories,
                    day = selectedDateValue.dayOfWeek,
                    time = when(mealTime) {
                        "Breakfast" -> MealTime.Breakfast
                        "Lunch" -> MealTime.Lunch
                        "Dinner" -> MealTime.Dinner
                        else -> MealTime.Snacks
                    },
                    description = description.ifEmpty { name },
                    recipeId = recipeId,
                    imageUrl = recipeId?.let { "https://source.unsplash.com/random/300x200?food" }
                )
                viewModel.addMeal(meal)
                showAddMealDialog = false
            }
        )
    }
    
    // Nutrition summary dialog
    if (showNutritionDialog) {
        NutritionSummaryDialog(
            dailyNutrition = dailyNutrition,
            selectedDate = selectedDateValue,
            onDismiss = { showNutritionDialog = false }
        )
    }
    
    // Share dialog
    if (showShareDialog) {
        AlertDialog(
            onDismissRequest = { showShareDialog = false },
            title = { Text("Share Meal Plan") },
            text = {
                Column {
                    Text("Choose how you want to share your meal plan:")
                    Spacer(modifier = Modifier.height(16.dp))
                    
                    Row(modifier = Modifier.fillMaxWidth()) {
                        Button(
                            onClick = {
                                shareMealPlan()
                                showShareDialog = false
                            },
                            modifier = Modifier.weight(1f)
                        ) {
                            Icon(Icons.Default.Share, contentDescription = null)
                            Spacer(modifier = Modifier.width(8.dp))
                            Text("Share")
                        }
                        
                        Spacer(modifier = Modifier.width(8.dp))
                        
                        Button(
                            onClick = {
                                saveMealPlan()
                                showShareDialog = false
                            },
                            modifier = Modifier.weight(1f)
                        ) {
                            Icon(Icons.Default.Save, contentDescription = null)
                            Spacer(modifier = Modifier.width(8.dp))
                            Text("Save")
                        }
                    }
                }
            },
            confirmButton = {},
            dismissButton = {
                TextButton(onClick = { showShareDialog = false }) {
                    Text("Cancel")
                }
            }
        )
    }
}

@Composable
fun CalendarView(
    dates: List<LocalDate>,
    selectedDate: LocalDate,
    onDateSelected: (LocalDate) -> Unit
) {
    val colors = MaterialTheme.colorScheme
    val typography = MaterialTheme.typography
    
    Column(
        modifier = Modifier
            .fillMaxWidth()
            .padding(16.dp)
    ) {
        // Month and year header
        Text(
            text = selectedDate.format(DateTimeFormatter.ofPattern("MMMM yyyy")),
            style = typography.titleMedium.copy(fontWeight = FontWeight.Bold),
            color = colors.onBackground
        )
        
        Spacer(modifier = Modifier.height(16.dp))
        
        // Days of week
        LazyRow(
            horizontalArrangement = Arrangement.spacedBy(8.dp),
            contentPadding = PaddingValues(vertical = 8.dp)
        ) {
            items(dates) { date ->
                DateItem(
                    date = date,
                    isSelected = date == selectedDate,
                    onDateSelected = onDateSelected
                )
            }
        }
        
        HorizontalDivider(
            color = colors.surfaceVariant,
            modifier = Modifier.padding(vertical = 16.dp)
        )
    }
}

@Composable
fun DateItem(
    date: LocalDate,
    isSelected: Boolean,
    onDateSelected: (LocalDate) -> Unit
) {
    val colors = MaterialTheme.colorScheme
    val typography = MaterialTheme.typography
    
    val today = LocalDate.now()
    val isToday = date.equals(today)
    
    val backgroundColor = when {
        isSelected -> colors.primary
        isToday -> colors.primaryContainer
        else -> colors.surface
    }
    
    val textColor = when {
        isSelected -> colors.onPrimary
        isToday -> colors.onPrimaryContainer
        else -> colors.onSurface
    }
    
    Column(
        horizontalAlignment = Alignment.CenterHorizontally,
        modifier = Modifier
            .width(45.dp)
            .clip(RoundedCornerShape(12.dp))
            .clickable { onDateSelected(date) }
            .background(backgroundColor)
            .padding(vertical = 8.dp, horizontal = 4.dp)
    ) {
        // Day of week (e.g., Mon)
        Text(
            text = date.dayOfWeek.getDisplayName(TextStyle.SHORT, Locale.getDefault()),
            style = typography.bodySmall,
            color = textColor
        )
        
        Spacer(modifier = Modifier.height(4.dp))
        
        // Day of month (e.g., 15)
        Text(
            text = date.dayOfMonth.toString(),
            style = typography.titleMedium.copy(fontWeight = FontWeight.Bold),
            color = textColor
        )
    }
}

@Composable
fun DailyMealPlan(
    date: LocalDate,
    meals: List<MealPlanItem>,
    onDeleteMeal: (String) -> Unit,
    onAddMeal: (mealTime: String, name: String, description: String, calories: Int, recipeId: String?) -> Unit,
    colors: ColorScheme,
    typography: Typography,
    onRecipeClick: (String?) -> Unit
) {
    val mealTimes = listOf("Breakfast", "Lunch", "Dinner", "Snacks")
    
    Column(
        modifier = Modifier
            .fillMaxWidth()
            .padding(horizontal = 16.dp)
    ) {
        Text(
            text = "Meals for ${date.format(DateTimeFormatter.ofPattern("EEEE, MMMM d"))}",
            style = typography.titleMedium.copy(fontWeight = FontWeight.Medium),
            color = colors.onBackground
        )
        
        Spacer(modifier = Modifier.height(16.dp))
        
        LazyColumn(
            verticalArrangement = Arrangement.spacedBy(16.dp),
            modifier = Modifier.fillMaxWidth()
        ) {
            items(mealTimes) { mealTime ->
                val mealForTime = meals.firstOrNull { it.name == mealTime }
                
                MealTimeCard(
                    mealTime = mealTime,
                    meal = mealForTime,
                    onDeleteMeal = onDeleteMeal,
                    onAddMeal = onAddMeal,
                    colors = colors,
                    typography = typography,
                    onRecipeClick = onRecipeClick
                )
            }
            
            item {
                Spacer(modifier = Modifier.height(80.dp)) // Space for FAB
            }
        }
    }
}

@Composable
fun MealTimeCard(
    mealTime: String,
    meal: MealPlanItem?,
    onDeleteMeal: (String) -> Unit,
    onAddMeal: (mealTime: String, name: String, description: String, calories: Int, recipeId: String?) -> Unit,
    colors: ColorScheme,
    typography: Typography,
    onRecipeClick: (String?) -> Unit
) {
    val mealTimeIcon = when(mealTime) {
        "Breakfast" -> Icons.Default.FreeBreakfast
        "Lunch" -> Icons.Default.LunchDining
        "Dinner" -> Icons.Default.DinnerDining
        else -> Icons.Default.Restaurant
    }
    
    var showAddMealDialog by remember { mutableStateOf(false) }
    
    Card(
        modifier = Modifier.fillMaxWidth(),
        colors = CardDefaults.cardColors(
            containerColor = colors.surface
        ),
        elevation = CardDefaults.cardElevation(defaultElevation = 0.dp)
    ) {
        Column(
            modifier = Modifier.fillMaxWidth()
        ) {
            // If we have an image, show it
            meal?.imageUrl?.let { imageUrl ->
                if (imageUrl.isNotEmpty()) {
                    AsyncImage(
                        model = imageUrl,
                        contentDescription = meal.description,
                        contentScale = ContentScale.Crop,
                        modifier = Modifier
                            .fillMaxWidth()
                            .height(120.dp)
                    )
                }
            }
            
            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(16.dp),
                verticalAlignment = Alignment.CenterVertically
            ) {
                // Meal time icon
                Box(
                    modifier = Modifier
                        .size(48.dp)
                        .clip(RoundedCornerShape(12.dp))
                        .background(colors.primaryContainer),
                    contentAlignment = Alignment.Center
                ) {
                    Icon(
                        imageVector = mealTimeIcon,
                        contentDescription = mealTime,
                        tint = colors.onPrimaryContainer,
                        modifier = Modifier.size(24.dp)
                    )
                }
                
                Spacer(modifier = Modifier.width(16.dp))
                
                // Meal info
                Column(
                    modifier = Modifier.weight(1f)
                ) {
                    Text(
                        text = mealTime,
                        style = typography.titleMedium.copy(fontWeight = FontWeight.Medium),
                        color = colors.onSurface
                    )
                    
                    if (meal != null) {
                        Spacer(modifier = Modifier.height(4.dp))
                        Text(
                            text = meal.description ?: meal.name,
                            style = typography.bodyMedium,
                            color = colors.onSurface.copy(alpha = 0.8f)
                        )
                        Spacer(modifier = Modifier.height(2.dp))
                        Text(
                            text = "${meal.calories} kcal",
                            style = typography.bodySmall,
                            color = colors.onSurface.copy(alpha = 0.6f)
                        )
                    } else {
                        Spacer(modifier = Modifier.height(4.dp))
                        Text(
                            text = "No meal planned",
                            style = typography.bodyMedium,
                            color = colors.onSurface.copy(alpha = 0.6f)
                        )
                    }
                }
                
                // Actions
                Row {
                    if (meal?.recipeId != null) {
                        IconButton(onClick = { onRecipeClick(meal.recipeId) }) {
                            Icon(
                                imageVector = Icons.Default.Restaurant,
                                contentDescription = "View recipe",
                                tint = colors.primary
                            )
                        }
                    }
                    
                    if (meal != null) {
                        IconButton(onClick = { meal.id.let { onDeleteMeal(it) } }) {
                            Icon(
                                imageVector = Icons.Default.Delete,
                                contentDescription = "Delete meal",
                                tint = colors.error.copy(alpha = 0.7f)
                            )
                        }
                    } else {
                        TextButton(
                            onClick = { showAddMealDialog = true },
                            colors = ButtonDefaults.textButtonColors(
                                contentColor = colors.primary
                            )
                        ) {
                            Text("Add")
                        }
                    }
                }
            }
        }
    }
    
    if (showAddMealDialog) {
        AddCustomMealDialog(
            mealTime = mealTime,
            onDismiss = { showAddMealDialog = false },
            onAddMeal = { name, description, calories, recipeId ->
                onAddMeal(mealTime, name, description, calories, recipeId)
                showAddMealDialog = false
            }
        )
    }
}

@Composable
fun AutoGenerateMealPlanDialog(
    onDismiss: () -> Unit,
    onGenerate: (calories: Int, dietType: String, allergies: List<String>) -> Unit
) {
    val colors = MaterialTheme.colorScheme
    val typography = MaterialTheme.typography

    // Preferences
    var targetCalories by remember { mutableStateOf(2000) }
    var selectedDietType by remember { mutableStateOf("Balanced") }
    val dietTypes = listOf("Balanced", "Low-carb", "High-protein", "Vegetarian", "Vegan")
    var showAdvancedOptions by remember { mutableStateOf(false) }
    
    // Allergies/restrictions
    var glutenFree by remember { mutableStateOf(false) }
    var nutFree by remember { mutableStateOf(false) }
    
    AlertDialog(
        onDismissRequest = onDismiss,
        title = {
            Text(
                text = "Auto-generate Meal Plan",
                style = typography.titleLarge.copy(fontWeight = FontWeight.Bold)
            )
        },
        text = {
            Column(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(vertical = 8.dp),
                verticalArrangement = Arrangement.spacedBy(16.dp)
            ) {
                Text(
                    text = "Let us create a personalized meal plan based on your preferences.",
                    style = typography.bodyMedium,
                    color = colors.onSurface.copy(alpha = 0.8f)
                )
                
                // Calorie target
                Text(
                    text = "Daily calories: $targetCalories",
                    style = typography.bodyMedium.copy(fontWeight = FontWeight.Medium)
                )
                Slider(
                    value = targetCalories.toFloat(),
                    onValueChange = { targetCalories = it.toInt() },
                    valueRange = 1200f..3500f,
                    steps = 23,
                    colors = SliderDefaults.colors(
                        thumbColor = colors.primary,
                        activeTrackColor = colors.primary
                    )
                )
                
                // Diet type
                Text(
                    text = "Diet type",
                    style = typography.bodyMedium.copy(fontWeight = FontWeight.Medium)
                )
                LazyRow(
                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                ) {
                    items(dietTypes) { dietType ->
                        val isSelected = dietType == selectedDietType
                        FilterChip(
                            selected = isSelected,
                            onClick = { selectedDietType = dietType },
                            label = { Text(dietType) },
                            colors = FilterChipDefaults.filterChipColors(
                                selectedContainerColor = colors.primaryContainer,
                                selectedLabelColor = colors.onPrimaryContainer
                            )
                        )
                    }
                }
                
                // Advanced options
                Row(
                    modifier = Modifier
                        .fillMaxWidth()
                        .clickable { showAdvancedOptions = !showAdvancedOptions },
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.SpaceBetween
                ) {
                    Text(
                        text = "Advanced options",
                        style = typography.bodyMedium.copy(fontWeight = FontWeight.Medium)
                    )
                    Icon(
                        imageVector = if (showAdvancedOptions) Icons.Default.ExpandLess else Icons.Default.ExpandMore,
                        contentDescription = if (showAdvancedOptions) "Hide advanced options" else "Show advanced options"
                    )
                }
                
                AnimatedVisibility(visible = showAdvancedOptions) {
                    Column(
                        verticalArrangement = Arrangement.spacedBy(8.dp)
                    ) {
                        // Allergies
                        Text(
                            text = "Food allergies/restrictions",
                            style = typography.bodySmall
                        )
                        
                        Row(
                            horizontalArrangement = Arrangement.spacedBy(8.dp)
                        ) {
                            FilterChip(
                                selected = glutenFree,
                                onClick = { glutenFree = !glutenFree },
                                label = { Text("Gluten-free") }
                            )
                            
                            FilterChip(
                                selected = nutFree,
                                onClick = { nutFree = !nutFree },
                                label = { Text("Nut-free") }
                            )
                        }
                    }
                }
            }
        },
        confirmButton = {
            Button(
                onClick = {
                    val allergies = mutableListOf<String>().apply {
                        if (glutenFree) add("gluten")
                        if (nutFree) add("nuts")
                    }
                    onGenerate(targetCalories, selectedDietType, allergies)
                },
                colors = ButtonDefaults.buttonColors(
                    containerColor = colors.primary
                )
            ) {
                Text("Generate")
            }
        },
        dismissButton = {
            TextButton(onClick = onDismiss) {
                Text("Cancel")
            }
        }
    )
}

@Composable
fun AddCustomMealDialog(
    mealTime: String,
    onDismiss: () -> Unit,
    onAddMeal: (name: String, description: String, calories: Int, recipeId: String?) -> Unit
) {
    val colors = MaterialTheme.colorScheme
    val typography = MaterialTheme.typography
    
    var mealName by remember { mutableStateOf("") }
    var mealDescription by remember { mutableStateOf("") }
    var caloriesText by remember { mutableStateOf("") }
    var recipeIdText by remember { mutableStateOf("") }
    
    val isAddEnabled = mealName.isNotEmpty() && caloriesText.isNotEmpty()
            
    AlertDialog(
        onDismissRequest = onDismiss,
        title = {
            Text(
                text = "Add $mealTime",
                style = typography.titleLarge.copy(fontWeight = FontWeight.Bold)
            )
        },
        text = {
            Column(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(vertical = 8.dp),
                verticalArrangement = Arrangement.spacedBy(16.dp)
            ) {
                OutlinedTextField(
                    value = mealName,
                    onValueChange = { mealName = it },
                    label = { Text("Meal Name") },
                    singleLine = true,
                    modifier = Modifier.fillMaxWidth()
                )
                
                OutlinedTextField(
                    value = mealDescription,
                    onValueChange = { mealDescription = it },
                    label = { Text("Description (optional)") },
                    modifier = Modifier.fillMaxWidth()
                )
                
                OutlinedTextField(
                    value = caloriesText,
                    onValueChange = { 
                        // Only allow numbers
                        if (it.isEmpty() || it.all { char -> char.isDigit() }) {
                            caloriesText = it
                        }
                    },
                    label = { Text("Calories") },
                    keyboardOptions = KeyboardOptions(
                        keyboardType = KeyboardType.Number
                    ),
                    singleLine = true,
                    modifier = Modifier.fillMaxWidth()
                )
                
                OutlinedTextField(
                    value = recipeIdText,
                    onValueChange = { recipeIdText = it },
                    label = { Text("Recipe ID (optional)") },
                    singleLine = true,
                    modifier = Modifier.fillMaxWidth()
                )
            }
        },
        confirmButton = {
            Button(
                onClick = {
                    val calories = caloriesText.toIntOrNull() ?: 0
                    val recipeId = if (recipeIdText.isBlank()) null else recipeIdText
                    onAddMeal(mealName, mealDescription, calories, recipeId)
                },
                enabled = isAddEnabled,
                colors = ButtonDefaults.buttonColors(
                    containerColor = colors.primary
                )
            ) {
                Text("Add Meal")
            }
        },
        dismissButton = {
            TextButton(onClick = onDismiss) {
                Text("Cancel")
            }
        }
    )
}

@Composable
fun AddCustomMealTimeDialog(
    onDismiss: () -> Unit,
    onSelectMealTime: (mealTime: String, name: String, description: String, calories: Int, recipeId: String?) -> Unit
) {
    val colors = MaterialTheme.colorScheme
    val typography = MaterialTheme.typography
    
    val mealTimes = listOf("Breakfast", "Lunch", "Dinner", "Snacks")
    var selectedMealTime by remember { mutableStateOf(mealTimes[0]) }
    
    var mealName by remember { mutableStateOf("") }
    var mealDescription by remember { mutableStateOf("") }
    var caloriesText by remember { mutableStateOf("") }
    var recipeIdText by remember { mutableStateOf("") }
    
    val isAddEnabled = mealName.isNotEmpty() && caloriesText.isNotEmpty()
    
    AlertDialog(
        onDismissRequest = onDismiss,
        title = {
            Text(
                text = "Add Custom Meal",
                style = typography.titleLarge.copy(fontWeight = FontWeight.Bold)
            )
        },
        text = {
            Column(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(vertical = 8.dp),
                verticalArrangement = Arrangement.spacedBy(16.dp)
            ) {
                // Meal time selection
                Text(
                    text = "Meal Time",
                    style = typography.bodyMedium.copy(fontWeight = FontWeight.Medium)
                )
                LazyRow(
                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                ) {
                    items(mealTimes) { mealTime ->
                        val isSelected = mealTime == selectedMealTime
                        FilterChip(
                            selected = isSelected,
                            onClick = { selectedMealTime = mealTime },
                            label = { Text(mealTime) },
                            colors = FilterChipDefaults.filterChipColors(
                                selectedContainerColor = colors.primaryContainer,
                                selectedLabelColor = colors.onPrimaryContainer
                            )
                        )
                    }
                }
                
                // Meal details
                OutlinedTextField(
                    value = mealName,
                    onValueChange = { mealName = it },
                    label = { Text("Meal Name") },
                    singleLine = true,
                    modifier = Modifier.fillMaxWidth()
                )
                
                OutlinedTextField(
                    value = mealDescription,
                    onValueChange = { mealDescription = it },
                    label = { Text("Description (optional)") },
                    modifier = Modifier.fillMaxWidth()
                )
                
                OutlinedTextField(
                    value = caloriesText,
                    onValueChange = { 
                        // Only allow numbers
                        if (it.isEmpty() || it.all { char -> char.isDigit() }) {
                            caloriesText = it
                        }
                    },
                    label = { Text("Calories") },
                    keyboardOptions = KeyboardOptions(
                        keyboardType = KeyboardType.Number
                    ),
                    singleLine = true,
                    modifier = Modifier.fillMaxWidth()
                )
                
                OutlinedTextField(
                    value = recipeIdText,
                    onValueChange = { recipeIdText = it },
                    label = { Text("Recipe ID (optional)") },
                    singleLine = true,
                    modifier = Modifier.fillMaxWidth()
                )
            }
        },
        confirmButton = {
            Button(
                onClick = {
                    val calories = caloriesText.toIntOrNull() ?: 0
                    val recipeId = if (recipeIdText.isBlank()) null else recipeIdText
                    onSelectMealTime(selectedMealTime, mealName, mealDescription, calories, recipeId)
                },
                enabled = isAddEnabled,
                colors = ButtonDefaults.buttonColors(
                    containerColor = colors.primary
                )
            ) {
                Text("Add Meal")
            }
        },
        dismissButton = {
            TextButton(onClick = onDismiss) {
                Text("Cancel")
            }
        }
    )
}

@Composable
fun NutritionSummaryDialog(
    dailyNutrition: Map<DayOfWeek, NutritionSummary>,
    selectedDate: LocalDate,
    onDismiss: () -> Unit
) {
    val colors = MaterialTheme.colorScheme
    val typography = MaterialTheme.typography
    
    val selectedDayNutrition = dailyNutrition[selectedDate.dayOfWeek]
    
    AlertDialog(
        onDismissRequest = onDismiss,
        title = {
            Text(
                text = "Nutrition Summary",
                style = typography.titleLarge.copy(fontWeight = FontWeight.Bold)
            )
        },
        text = {
            Column(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(vertical = 8.dp),
                verticalArrangement = Arrangement.spacedBy(16.dp)
            ) {
                Text(
                    text = "Daily Nutrition for ${selectedDate.format(DateTimeFormatter.ofPattern("EEEE, MMMM d"))}",
                    style = typography.bodyMedium,
                    color = colors.onSurface
                )
                
                if (selectedDayNutrition != null) {
                    // Calories
                    NutritionProgressBar(
                        label = "Calories",
                        value = selectedDayNutrition.calories,
                        maxValue = 2500, // This could be customizable
                        colors = colors,
                        typography = typography,
                        valueLabel = "${selectedDayNutrition.calories} kcal"
                    )
                    
                    // Macronutrients
                    NutritionProgressBar(
                        label = "Protein",
                        value = selectedDayNutrition.protein,
                        maxValue = 150,
                        colors = colors,
                        typography = typography,
                        valueLabel = "${selectedDayNutrition.protein}g",
                        progressColor = Color(0xFF4CAF50) // Green
                    )
                    
                    NutritionProgressBar(
                        label = "Carbs",
                        value = selectedDayNutrition.carbs,
                        maxValue = 300,
                        colors = colors,
                        typography = typography,
                        valueLabel = "${selectedDayNutrition.carbs}g",
                        progressColor = Color(0xFFFFC107) // Amber
                    )
                    
                    NutritionProgressBar(
                        label = "Fat",
                        value = selectedDayNutrition.fat,
                        maxValue = 80,
                        colors = colors,
                        typography = typography,
                        valueLabel = "${selectedDayNutrition.fat}g",
                        progressColor = Color(0xFFE91E63) // Pink
                    )
                    
                    // Macros distribution
                    Text(
                        text = "Macronutrient Distribution",
                        style = typography.bodyMedium.copy(fontWeight = FontWeight.Medium),
                        modifier = Modifier.padding(top = 8.dp)
                    )
                    
                    val totalMacros = selectedDayNutrition.protein + selectedDayNutrition.carbs + selectedDayNutrition.fat
                    val proteinPercentage = if (totalMacros > 0) selectedDayNutrition.protein * 100f / totalMacros else 0f
                    val carbsPercentage = if (totalMacros > 0) selectedDayNutrition.carbs * 100f / totalMacros else 0f
                    val fatPercentage = if (totalMacros > 0) selectedDayNutrition.fat * 100f / totalMacros else 0f
                    
                    // Render distribution bar only for positive segments to avoid weight(0f)
                    if (totalMacros > 0f) {
                        Row(
                            modifier = Modifier
                                .fillMaxWidth()
                                .height(24.dp)
                                .clip(RoundedCornerShape(12.dp))
                        ) {
                            if (proteinPercentage > 0f) {
                                Box(
                                    modifier = Modifier
                                        .weight(proteinPercentage)
                                        .fillMaxHeight()
                                        .background(Color(0xFF4CAF50))
                                )
                            }
                            if (carbsPercentage > 0f) {
                                Box(
                                    modifier = Modifier
                                        .weight(carbsPercentage)
                                        .fillMaxHeight()
                                        .background(Color(0xFFFFC107))
                                )
                            }
                            if (fatPercentage > 0f) {
                                Box(
                                    modifier = Modifier
                                        .weight(fatPercentage)
                                        .fillMaxHeight()
                                        .background(Color(0xFFE91E63))
                                )
                            }
                        }
                    } else {
                        // No macro data: show an empty placeholder bar
                        Box(
                            modifier = Modifier
                                .fillMaxWidth()
                                .height(24.dp)
                                .clip(RoundedCornerShape(12.dp))
                                .background(colors.surfaceVariant)
                        )
                    }
                    
                    // Legend
                    Row(
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(top = 8.dp),
                        horizontalArrangement = Arrangement.SpaceBetween
                    ) {
                        Row(
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Box(
                                modifier = Modifier
                                    .size(12.dp)
                                    .background(Color(0xFF4CAF50), CircleShape)
                            )
                            Spacer(modifier = Modifier.width(4.dp))
                            Text(
                                text = "Protein ${proteinPercentage.toInt()}%",
                                style = typography.bodySmall
                            )
                        }
                        
                        Row(
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Box(
                                modifier = Modifier
                                    .size(12.dp)
                                    .background(Color(0xFFFFC107), CircleShape)
                            )
                            Spacer(modifier = Modifier.width(4.dp))
                            Text(
                                text = "Carbs ${carbsPercentage.toInt()}%",
                                style = typography.bodySmall
                            )
                        }
                        
                        Row(
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Box(
                                modifier = Modifier
                                    .size(12.dp)
                                    .background(Color(0xFFE91E63), CircleShape)
                            )
                            Spacer(modifier = Modifier.width(4.dp))
                            Text(
                                text = "Fat ${fatPercentage.toInt()}%",
                                style = typography.bodySmall
                            )
                        }
                    }
                } else {
                    // No nutrition data
                    Text(
                        text = "No meals planned for this day.",
                        style = typography.bodyMedium,
                        color = colors.onSurface.copy(alpha = 0.6f),
                        textAlign = TextAlign.Center,
                        modifier = Modifier.fillMaxWidth()
                    )
                }
            }
        },
        confirmButton = {
            Button(
                onClick = onDismiss,
                colors = ButtonDefaults.buttonColors(
                    containerColor = colors.primary
                )
            ) {
                Text("Close")
            }
        }
    )
}

@Composable
fun NutritionProgressBar(
    label: String,
    value: Int,
    maxValue: Int,
    colors: ColorScheme,
    typography: Typography,
    valueLabel: String,
    progressColor: Color = colors.primary
) {
    val progress = (value.toFloat() / maxValue).coerceIn(0f, 1f)
    
    Column(
        modifier = Modifier.fillMaxWidth()
    ) {
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically
        ) {
            Text(
                text = label,
                style = typography.bodyMedium
            )
            Text(
                text = valueLabel,
                style = typography.bodySmall
            )
        }
        
        Spacer(modifier = Modifier.height(4.dp))
        
        LinearProgressIndicator(
            progress = { progress },
            modifier = Modifier.fillMaxWidth().height(8.dp).clip(RoundedCornerShape(4.dp)),
            color = progressColor,
            trackColor = colors.surfaceVariant
        )
    }
} 