package com.thenewkenya.ingrediet.feature.mealplanner

import androidx.compose.animation.AnimatedVisibility
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.lifecycle.viewmodel.compose.viewModel
import androidx.navigation.NavController
import coil3.compose.AsyncImage
import java.time.DayOfWeek
import java.time.LocalDate
import java.time.format.DateTimeFormatter
import java.time.format.TextStyle
import java.time.temporal.ChronoUnit
import java.util.Locale

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun MealPlannerScreen(
    navController: NavController,
    viewModel: MealPlannerViewModel = viewModel(
        factory = MealPlannerViewModelFactory(LocalContext.current)
    )
) {
    val colors = MaterialTheme.colorScheme
    val typography = MaterialTheme.typography
    
    // Track the selected date
    var selectedDate by remember { mutableStateOf(LocalDate.now()) }
    
    // Track if auto-generation dialog is visible
    var showAutoGenerateDialog by remember { mutableStateOf(false) }
    
    // Collect state values from the ViewModel
    val currentWeek by viewModel.currentWeek.collectAsState()
    val mealPlans by viewModel.mealPlans.collectAsState()
    val dailyNutrition by viewModel.dailyNutrition.collectAsState()
    val isLoading by viewModel.isLoading.collectAsState()
    val isGenerating by viewModel.isGenerating.collectAsState()
    val error by viewModel.error.collectAsState()
    val generationProgress by viewModel.generationProgress.collectAsState()
    val generationStage by viewModel.generationStage.collectAsState()
    
    // Generate dates for the weekly calendar
    val calendarDates = remember(selectedDate) {
        val firstDayOfWeek = selectedDate.with(DayOfWeek.MONDAY)
        (0..6).map { firstDayOfWeek.plusDays(it.toLong()) }
    }

    Scaffold(
        containerColor = colors.background,
        topBar = {
            TopAppBar(
                title = { 
                    Text(
                        text = "Meal Planner",
                        style = typography.titleLarge.copy(fontWeight = FontWeight.Bold)
                    ) 
                },
                navigationIcon = {
                    IconButton(onClick = { navController.navigateUp() }) {
                        Icon(
                            imageVector = Icons.AutoMirrored.Filled.ArrowBack,
                            contentDescription = "Back",
                            tint = colors.onBackground
                        )
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = colors.background,
                    titleContentColor = colors.onBackground
                ),
                actions = {
                    IconButton(onClick = { showAutoGenerateDialog = true }) {
                        Icon(
                            imageVector = Icons.Default.AutoAwesome,
                            contentDescription = "Auto-generate meal plan",
                            tint = colors.onBackground
                        )
                    }
                }
            )
        },
        floatingActionButton = {
            FloatingActionButton(
                onClick = { /* TODO: Add custom meal to plan */ },
                containerColor = colors.primary,
                contentColor = colors.onPrimary
            ) {
                Icon(Icons.Default.Add, contentDescription = "Add Meal")
            }
        }
    ) { paddingValues ->
        Box(
            modifier = Modifier
                .fillMaxSize()
                .padding(paddingValues)
                .background(colors.background)
        ) {
            Column(
                modifier = Modifier.fillMaxSize()
            ) {
                // Weekly calendar
                CalendarView(
                    dates = calendarDates,
                    selectedDate = selectedDate,
                    onDateSelected = { selectedDate = it }
                )
                
                // Show content based on state
                when {
                    isLoading || isGenerating -> {
                        Box(
                            contentAlignment = Alignment.Center,
                            modifier = Modifier
                                .fillMaxSize()
                                .padding(16.dp)
                        ) {
                            Column(
                                horizontalAlignment = Alignment.CenterHorizontally,
                                verticalArrangement = Arrangement.spacedBy(16.dp)
                            ) {
                                if (isGenerating) {
                                    // Show generation progress with a linear progress indicator
                                    Column(
                                        horizontalAlignment = Alignment.CenterHorizontally,
                                        verticalArrangement = Arrangement.spacedBy(8.dp),
                                        modifier = Modifier
                                            .padding(horizontal = 32.dp)
                                            .fillMaxWidth()
                                    ) {
                                        LinearProgressIndicator(
                                            progress = { generationProgress },
                                            modifier = Modifier.fillMaxWidth(),
                                            color = colors.primary,
                                            trackColor = colors.primaryContainer
                                        )
                                        
                                        Text(
                                            text = generationStage ?: "Generating your meal plan...",
                                            style = typography.bodyMedium,
                                            color = colors.onBackground,
                                            textAlign = TextAlign.Center
                                        )
                                        
                                        Text(
                                            text = "${(generationProgress * 100).toInt()}%",
                                            style = typography.labelMedium,
                                            color = colors.primary,
                                            textAlign = TextAlign.Center,
                                            modifier = Modifier.padding(top = 4.dp)
                                        )
                                    }
                                } else {
                                    // Regular loading indicator
                                    CircularProgressIndicator(color = colors.primary)
                                    Text(
                                        text = "Loading...",
                                        style = typography.bodyLarge,
                                        color = colors.onBackground
                                    )
                                }
                            }
                        }
                    }
                    
                    error != null -> {
                        Box(
                            contentAlignment = Alignment.Center,
                            modifier = Modifier
                                .fillMaxSize()
                                .padding(16.dp)
                        ) {
                            Column(
                                horizontalAlignment = Alignment.CenterHorizontally,
                                verticalArrangement = Arrangement.spacedBy(16.dp)
                            ) {
                                Icon(
                                    imageVector = Icons.Default.Error,
                                    contentDescription = null,
                                    tint = colors.error,
                                    modifier = Modifier.size(48.dp)
                                )
                                Text(
                                    text = error ?: "An unexpected error occurred",
                                    style = typography.bodyLarge,
                                    color = colors.error,
                                    textAlign = TextAlign.Center
                                )
                                Button(
                                    onClick = { /* Retry loading */ },
                                    colors = ButtonDefaults.buttonColors(
                                        containerColor = colors.primary
                                    )
                                ) {
                                    Text("Retry")
                                }
                            }
                        }
                    }
                    
                    else -> {
                        // Daily meal plan
                        DailyMealPlan(
                            date = selectedDate,
                            meals = viewModel.getMealsForDay(selectedDate.dayOfWeek),
                            onDeleteMeal = { viewModel.removeMeal(it) },
                            colors = colors,
                            typography = typography,
                            onRecipeClick = { recipeId -> 
                                if (recipeId != null) {
                                    navController.navigate("recipe/$recipeId")
                                }
                            }
                        )
                    }
                }
            }
        }
    }
    
    // Auto-generate meal plan dialog
    if (showAutoGenerateDialog) {
        AutoGenerateMealPlanDialog(
            onDismiss = { showAutoGenerateDialog = false },
            onGenerate = { calories, dietType, allergies -> 
                viewModel.generateMealPlan(calories, dietType, allergies)
                showAutoGenerateDialog = false 
            }
        )
    }
}

@Composable
fun CalendarView(
    dates: List<LocalDate>,
    selectedDate: LocalDate,
    onDateSelected: (LocalDate) -> Unit
) {
    val colors = MaterialTheme.colorScheme
    val typography = MaterialTheme.typography
    
    Column(
        modifier = Modifier
            .fillMaxWidth()
            .padding(16.dp)
    ) {
        // Month and year header
        Text(
            text = selectedDate.format(DateTimeFormatter.ofPattern("MMMM yyyy")),
            style = typography.titleMedium.copy(fontWeight = FontWeight.Bold),
            color = colors.onBackground
        )
        
        Spacer(modifier = Modifier.height(16.dp))
        
        // Days of week
        LazyRow(
            horizontalArrangement = Arrangement.spacedBy(8.dp),
            contentPadding = PaddingValues(vertical = 8.dp)
        ) {
            items(dates) { date ->
                DateItem(
                    date = date,
                    isSelected = date == selectedDate,
                    onDateSelected = onDateSelected
                )
            }
        }
        
        HorizontalDivider(
            color = colors.surfaceVariant,
            modifier = Modifier.padding(vertical = 16.dp)
        )
    }
}

@Composable
fun DateItem(
    date: LocalDate,
    isSelected: Boolean,
    onDateSelected: (LocalDate) -> Unit
) {
    val colors = MaterialTheme.colorScheme
    val typography = MaterialTheme.typography
    
    val today = LocalDate.now()
    val isToday = date.equals(today)
    
    val backgroundColor = when {
        isSelected -> colors.primary
        isToday -> colors.primaryContainer
        else -> colors.surface
    }
    
    val textColor = when {
        isSelected -> colors.onPrimary
        isToday -> colors.onPrimaryContainer
        else -> colors.onSurface
    }
    
    Column(
        horizontalAlignment = Alignment.CenterHorizontally,
        modifier = Modifier
            .width(45.dp)
            .clip(RoundedCornerShape(12.dp))
            .clickable { onDateSelected(date) }
            .background(backgroundColor)
            .padding(vertical = 8.dp, horizontal = 4.dp)
    ) {
        // Day of week (e.g., Mon)
        Text(
            text = date.dayOfWeek.getDisplayName(TextStyle.SHORT, Locale.getDefault()),
            style = typography.bodySmall,
            color = textColor
        )
        
        Spacer(modifier = Modifier.height(4.dp))
        
        // Day of month (e.g., 15)
        Text(
            text = date.dayOfMonth.toString(),
            style = typography.titleMedium.copy(fontWeight = FontWeight.Bold),
            color = textColor
        )
    }
}

@Composable
fun DailyMealPlan(
    date: LocalDate,
    meals: List<MealPlanItem>,
    onDeleteMeal: (String) -> Unit,
    colors: ColorScheme,
    typography: Typography,
    onRecipeClick: (Int?) -> Unit
) {
    val mealTimes = listOf("Breakfast", "Lunch", "Dinner", "Snacks")
    
    Column(
        modifier = Modifier
            .fillMaxWidth()
            .padding(horizontal = 16.dp)
    ) {
        Text(
            text = "Meals for ${date.format(DateTimeFormatter.ofPattern("EEEE, MMMM d"))}",
            style = typography.titleMedium.copy(fontWeight = FontWeight.Medium),
            color = colors.onBackground
        )
        
        Spacer(modifier = Modifier.height(16.dp))
        
        LazyColumn(
            verticalArrangement = Arrangement.spacedBy(16.dp),
            modifier = Modifier.fillMaxWidth()
        ) {
            items(mealTimes) { mealTime ->
                val mealForTime = meals.firstOrNull { it.name == mealTime }
                
                MealTimeCard(
                    mealTime = mealTime,
                    meal = mealForTime,
                    onDeleteMeal = onDeleteMeal,
                    colors = colors,
                    typography = typography,
                    onRecipeClick = onRecipeClick
                )
            }
            
            item {
                Spacer(modifier = Modifier.height(80.dp)) // Space for FAB
            }
        }
    }
}

@Composable
fun MealTimeCard(
    mealTime: String,
    meal: MealPlanItem?,
    onDeleteMeal: (String) -> Unit,
    colors: ColorScheme,
    typography: Typography,
    onRecipeClick: (Int?) -> Unit
) {
    val mealTimeIcon = when(mealTime) {
        "Breakfast" -> Icons.Default.FreeBreakfast
        "Lunch" -> Icons.Default.LunchDining
        "Dinner" -> Icons.Default.DinnerDining
        else -> Icons.Default.Restaurant
    }
    
    Card(
        modifier = Modifier.fillMaxWidth(),
        colors = CardDefaults.cardColors(
            containerColor = colors.surface
        ),
        elevation = CardDefaults.cardElevation(defaultElevation = 0.dp)
    ) {
        Column(
            modifier = Modifier.fillMaxWidth()
        ) {
            // If we have an image, show it
            meal?.imageUrl?.let { imageUrl ->
                if (imageUrl.isNotEmpty()) {
                    AsyncImage(
                        model = imageUrl,
                        contentDescription = meal.description,
                        contentScale = ContentScale.Crop,
                        modifier = Modifier
                            .fillMaxWidth()
                            .height(120.dp)
                    )
                }
            }
            
            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(16.dp),
                verticalAlignment = Alignment.CenterVertically
            ) {
                // Meal time icon
                Box(
                    modifier = Modifier
                        .size(48.dp)
                        .clip(RoundedCornerShape(12.dp))
                        .background(colors.primaryContainer),
                    contentAlignment = Alignment.Center
                ) {
                    Icon(
                        imageVector = mealTimeIcon,
                        contentDescription = mealTime,
                        tint = colors.onPrimaryContainer,
                        modifier = Modifier.size(24.dp)
                    )
                }
                
                Spacer(modifier = Modifier.width(16.dp))
                
                // Meal info
                Column(
                    modifier = Modifier.weight(1f)
                ) {
                    Text(
                        text = mealTime,
                        style = typography.titleMedium.copy(fontWeight = FontWeight.Medium),
                        color = colors.onSurface
                    )
                    
                    if (meal != null) {
                        Spacer(modifier = Modifier.height(4.dp))
                        Text(
                            text = meal.description ?: meal.name,
                            style = typography.bodyMedium,
                            color = colors.onSurface.copy(alpha = 0.8f)
                        )
                        Spacer(modifier = Modifier.height(2.dp))
                        Text(
                            text = "${meal.calories} kcal",
                            style = typography.bodySmall,
                            color = colors.onSurface.copy(alpha = 0.6f)
                        )
                    } else {
                        Spacer(modifier = Modifier.height(4.dp))
                        Text(
                            text = "No meal planned",
                            style = typography.bodyMedium,
                            color = colors.onSurface.copy(alpha = 0.6f)
                        )
                    }
                }
                
                // Actions
                Row {
                    if (meal?.recipeId != null) {
                        IconButton(onClick = { onRecipeClick(meal.recipeId) }) {
                            Icon(
                                imageVector = Icons.Default.Restaurant,
                                contentDescription = "View recipe",
                                tint = colors.primary
                            )
                        }
                    }
                    
                    if (meal != null) {
                        IconButton(onClick = { meal.id.let { onDeleteMeal(it) } }) {
                            Icon(
                                imageVector = Icons.Default.Delete,
                                contentDescription = "Delete meal",
                                tint = colors.error.copy(alpha = 0.7f)
                            )
                        }
                    } else {
                        TextButton(
                            onClick = { /* TODO: Add meal */ },
                            colors = ButtonDefaults.textButtonColors(
                                contentColor = colors.primary
                            )
                        ) {
                            Text("Add")
                        }
                    }
                }
            }
        }
    }
}

@Composable
fun AutoGenerateMealPlanDialog(
    onDismiss: () -> Unit,
    onGenerate: (calories: Int, dietType: String, allergies: List<String>) -> Unit
) {
    val colors = MaterialTheme.colorScheme
    val typography = MaterialTheme.typography

    // Preferences
    var targetCalories by remember { mutableStateOf(2000) }
    var selectedDietType by remember { mutableStateOf("Balanced") }
    val dietTypes = listOf("Balanced", "Low-carb", "High-protein", "Vegetarian", "Vegan")
    var showAdvancedOptions by remember { mutableStateOf(false) }
    
    // Allergies/restrictions
    var glutenFree by remember { mutableStateOf(false) }
    var nutFree by remember { mutableStateOf(false) }
    
    AlertDialog(
        onDismissRequest = onDismiss,
        title = {
            Text(
                text = "Auto-generate Meal Plan",
                style = typography.titleLarge.copy(fontWeight = FontWeight.Bold)
            )
        },
        text = {
            Column(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(vertical = 8.dp),
                verticalArrangement = Arrangement.spacedBy(16.dp)
            ) {
                Text(
                    text = "Let us create a personalized meal plan based on your preferences.",
                    style = typography.bodyMedium,
                    color = colors.onSurface.copy(alpha = 0.8f)
                )
                
                // Calorie target
                Text(
                    text = "Daily calories: $targetCalories",
                    style = typography.bodyMedium.copy(fontWeight = FontWeight.Medium)
                )
                Slider(
                    value = targetCalories.toFloat(),
                    onValueChange = { targetCalories = it.toInt() },
                    valueRange = 1200f..3500f,
                    steps = 23,
                    colors = SliderDefaults.colors(
                        thumbColor = colors.primary,
                        activeTrackColor = colors.primary
                    )
                )
                
                // Diet type
                Text(
                    text = "Diet type",
                    style = typography.bodyMedium.copy(fontWeight = FontWeight.Medium)
                )
                LazyRow(
                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                ) {
                    items(dietTypes) { dietType ->
                        val isSelected = dietType == selectedDietType
                        FilterChip(
                            selected = isSelected,
                            onClick = { selectedDietType = dietType },
                            label = { Text(dietType) },
                            colors = FilterChipDefaults.filterChipColors(
                                selectedContainerColor = colors.primaryContainer,
                                selectedLabelColor = colors.onPrimaryContainer
                            )
                        )
                    }
                }
                
                // Advanced options
                Row(
                    modifier = Modifier
                        .fillMaxWidth()
                        .clickable { showAdvancedOptions = !showAdvancedOptions },
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.SpaceBetween
                ) {
                    Text(
                        text = "Advanced options",
                        style = typography.bodyMedium.copy(fontWeight = FontWeight.Medium)
                    )
                    Icon(
                        imageVector = if (showAdvancedOptions) Icons.Default.ExpandLess else Icons.Default.ExpandMore,
                        contentDescription = if (showAdvancedOptions) "Hide advanced options" else "Show advanced options"
                    )
                }
                
                AnimatedVisibility(visible = showAdvancedOptions) {
                    Column(
                        verticalArrangement = Arrangement.spacedBy(8.dp)
                    ) {
                        // Allergies
                        Text(
                            text = "Food allergies/restrictions",
                            style = typography.bodySmall
                        )
                        
                        Row(
                            horizontalArrangement = Arrangement.spacedBy(8.dp)
                        ) {
                            FilterChip(
                                selected = glutenFree,
                                onClick = { glutenFree = !glutenFree },
                                label = { Text("Gluten-free") }
                            )
                            
                            FilterChip(
                                selected = nutFree,
                                onClick = { nutFree = !nutFree },
                                label = { Text("Nut-free") }
                            )
                        }
                    }
                }
            }
        },
        confirmButton = {
            Button(
                onClick = {
                    val allergies = mutableListOf<String>().apply {
                        if (glutenFree) add("gluten")
                        if (nutFree) add("nuts")
                    }
                    onGenerate(targetCalories, selectedDietType, allergies)
                },
                colors = ButtonDefaults.buttonColors(
                    containerColor = colors.primary
                )
            ) {
                Text("Generate")
            }
        },
        dismissButton = {
            TextButton(onClick = onDismiss) {
                Text("Cancel")
            }
        }
    )
} 