@file:OptIn(androidx.compose.material3.ExperimentalMaterial3Api::class)
package com.thenewkenya.ingrediet.feature.mealplanner

import android.content.Intent
import android.widget.Toast
import androidx.compose.animation.AnimatedVisibility
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.foundation.text.KeyboardOptions
import androidx.lifecycle.viewmodel.compose.viewModel
import androidx.navigation.NavController
import coil3.compose.AsyncImage
import java.time.DayOfWeek
import java.time.LocalDate
import java.time.format.DateTimeFormatter
import java.time.format.TextStyle
import java.time.temporal.ChronoUnit
import java.util.Locale
import kotlinx.coroutines.launch

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun MealPlannerScreen(
    navController: NavController,
    viewModel: MealPlannerViewModel = viewModel(
        factory = MealPlannerViewModelFactory(LocalContext.current)
    )
) {
    val colors = MaterialTheme.colorScheme
    val typography = MaterialTheme.typography
    val context = LocalContext.current
    
    // Collect state values from the ViewModel
    val currentWeek by viewModel.currentWeek.collectAsState()
    val mealPlans by viewModel.mealPlans.collectAsState()
    val dailyNutrition by viewModel.dailyNutrition.collectAsState()
    val isLoading by viewModel.isLoading.collectAsState()
    val isGenerating by viewModel.isGenerating.collectAsState()
    val error by viewModel.error.collectAsState()
    val generationProgress by viewModel.generationProgress.collectAsState()
    val generationStage by viewModel.generationStage.collectAsState()
    
    // Debug logging for state changes
    LaunchedEffect(mealPlans) {
        android.util.Log.d("MealPlannerScreen", "MealPlans state changed: ${mealPlans.size} days")
        mealPlans.forEach { (day, meals) ->
            android.util.Log.d("MealPlannerScreen", "$day: ${meals.size} meals")
        }
    }
    
    LaunchedEffect(isGenerating) {
        android.util.Log.d("MealPlannerScreen", "Generation state changed: isGenerating=$isGenerating")
    }
    
    // Generate dates for the weekly calendar
    val selectedDate = remember { mutableStateOf(LocalDate.now()) }
    val selectedDateValue by selectedDate
    
    val startOfWeek = remember(selectedDateValue) {
        selectedDateValue.with(DayOfWeek.MONDAY)
    }
    
    val calendarDates = remember(startOfWeek) {
        (0..6).map { startOfWeek.plusDays(it.toLong()) }
    }
    
    // Dialog state
    var showAutoGenerateDialog by remember { mutableStateOf(false) }
    var showAddMealDialog by remember { mutableStateOf(false) }
    var showNutritionDialog by remember { mutableStateOf(false) }
    var showShareDialog by remember { mutableStateOf(false) }
    
    // For navigation between weeks
    fun navigateToWeek(direction: Int) {
        selectedDate.value = selectedDateValue.plusWeeks(direction.toLong())
    }
    

    
    val snackbarHostState = remember { androidx.compose.material3.SnackbarHostState() }
    val scope = rememberCoroutineScope()
    Scaffold(
        containerColor = colors.background,
        snackbarHost = { androidx.compose.material3.SnackbarHost(snackbarHostState) },
        topBar = {
            TopAppBar(
                title = { 
                    Text(
                        text = "Meal Planner",
                        style = typography.titleLarge.copy(fontWeight = FontWeight.Bold)
                    )
                },
                navigationIcon = {
                    IconButton(onClick = { navController.navigateUp() }) {
                        Icon(
                            imageVector = Icons.AutoMirrored.Filled.ArrowBack,
                            contentDescription = "Back",
                            tint = colors.onBackground
                        )
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = colors.background,
                    titleContentColor = colors.onBackground
                ),
                actions = {
                    // Nutrition summary button
                    IconButton(onClick = { showNutritionDialog = true }) {
                        Icon(
                            imageVector = Icons.Default.BarChart,
                            contentDescription = "Nutrition summary",
                            tint = colors.onBackground
                        )
                    }
                    // Auto-generate meal plan button
                    IconButton(onClick = { showAutoGenerateDialog = true }) {
                        Icon(
                            imageVector = Icons.Default.AutoAwesome,
                            contentDescription = "Auto-generate meal plan",
                            tint = colors.onBackground
                        )
                    }
                }
            )
        },
        floatingActionButton = {
            FloatingActionButton(
                onClick = { showAddMealDialog = true },
                containerColor = colors.primary,
                contentColor = colors.onPrimary
            ) {
                Icon(Icons.Default.Add, contentDescription = "Add Meal")
            }
        }
    ) { paddingValues ->
        Box(
            modifier = Modifier
                .fillMaxSize()
                .padding(paddingValues)
                .background(colors.background)
        ) {
            Column(
                modifier = Modifier.fillMaxSize()
            ) {
                // Weekly calendar
                CalendarView(
                    dates = calendarDates,
                    selectedDate = selectedDateValue,
                    onDateSelected = { selectedDate.value = it }
                )
                
                // Show content based on state
                when {
                    isLoading || isGenerating -> {
                        Box(
                            contentAlignment = Alignment.Center,
                            modifier = Modifier
                                .fillMaxSize()
                                .padding(16.dp)
                        ) {
                            Column(
                                horizontalAlignment = Alignment.CenterHorizontally,
                                verticalArrangement = Arrangement.spacedBy(16.dp)
                            ) {
                                if (isGenerating) {
                                    // Show generation progress with a linear progress indicator
                                    Column(
                                        horizontalAlignment = Alignment.CenterHorizontally,
                                        verticalArrangement = Arrangement.spacedBy(8.dp),
                                        modifier = Modifier
                                            .padding(horizontal = 32.dp)
                                            .fillMaxWidth()
                                    ) {
                                        LinearProgressIndicator(
                                            progress = { generationProgress },
                                            modifier = Modifier.fillMaxWidth(),
                                            color = colors.primary,
                                            trackColor = colors.primaryContainer
                                        )
                                        
                                        Text(
                                            text = generationStage ?: "Generating your meal plan...",
                                            style = typography.bodyMedium,
                                            color = colors.onBackground,
                                            textAlign = TextAlign.Center
                                        )
                                        
                                        Text(
                                            text = "${(generationProgress * 100).toInt()}%",
                                            style = typography.labelMedium,
                                            color = colors.primary,
                                            textAlign = TextAlign.Center,
                                            modifier = Modifier.padding(top = 4.dp)
                                        )
                                    }
                                } else {
                                    // Regular loading indicator
                                    CircularProgressIndicator(color = colors.primary)
                                    Text(
                                        text = "Loading...",
                                        style = typography.bodyLarge,
                                        color = colors.onBackground
                                    )
                                }
                            }
                        }
                    }
                    
                    error != null -> {
                        Box(
                            contentAlignment = Alignment.Center,
                            modifier = Modifier
                                .fillMaxSize()
                                .padding(16.dp)
                        ) {
                            Column(
                                horizontalAlignment = Alignment.CenterHorizontally,
                                verticalArrangement = Arrangement.spacedBy(16.dp)
                            ) {
                                Icon(
                                    imageVector = Icons.Default.Error,
                                    contentDescription = null,
                                    tint = colors.error,
                                    modifier = Modifier.size(48.dp)
                                )
                                Text(
                                    text = error ?: "An unexpected error occurred",
                                    style = typography.bodyLarge,
                                    color = colors.error,
                                    textAlign = TextAlign.Center
                                )
                                Button(
                                    onClick = { /* Retry loading */ },
                                    colors = ButtonDefaults.buttonColors(
                                        containerColor = colors.primary
                                    )
                                ) {
                                    Text("Retry")
                                }
                            }
                        }
                    }
                    
                    else -> {
                        // Daily meal plan
                        val mealsForDay = mealPlans[selectedDateValue.dayOfWeek] ?: emptyList()
                        android.util.Log.d("MealPlannerScreen", "Rendering DailyMealPlan for ${selectedDateValue.dayOfWeek}: ${mealsForDay.size} meals")
                        mealsForDay.forEach { meal ->
                            android.util.Log.d("MealPlannerScreen", "Meal: ${meal.time.name} - ${meal.name}")
                        }
                        
                        DailyMealPlan(
                            date = selectedDateValue,
                            meals = mealsForDay,
                            onDeleteMeal = { meal ->
                                viewModel.removeMeal(meal.id)
                                scope.launch {
                                    val res = snackbarHostState.showSnackbar(
                                        message = "Meal deleted",
                                        actionLabel = "Undo",
                                        duration = androidx.compose.material3.SnackbarDuration.Short
                                    )
                                    if (res == androidx.compose.material3.SnackbarResult.ActionPerformed) {
                                        viewModel.addMeal(meal)
                                    }
                                }
                            },
                            onAddMeal = { mealTime, name, description, calories, recipeId ->
                                val meal = MealPlanItem(
                                    id = "${selectedDateValue.dayOfWeek}_${mealTime}_${System.currentTimeMillis()}",
                                    name = mealTime,
                                    calories = calories,
                                    day = selectedDateValue.dayOfWeek,
                                    time = when(mealTime) {
                                        "Breakfast" -> MealTime.Breakfast
                                        "Lunch" -> MealTime.Lunch
                                        "Dinner" -> MealTime.Dinner
                                        else -> MealTime.Snacks
                                    },
                                    description = description.ifEmpty { name },
                                    recipeId = recipeId,
                                    imageUrl = recipeId?.let { "https://source.unsplash.com/random/300x200?food" }
                                )
                                viewModel.addMeal(meal)
                            },
                            colors = colors,
                            typography = typography,
                            onRecipeClick = { recipeId -> 
                                if (recipeId != null) {
                                    navController.navigate("recipe/$recipeId")
                                }
                            },
                            onUpdateMeal = { updated -> viewModel.updateMeal(updated) },
                            onShowAddSheet = { showAddMealDialog = true }
                        )
                        // Hydration nudge between sections
                        Spacer(modifier = Modifier.height(8.dp))
                        Card(
                            modifier = Modifier
                                .fillMaxWidth()
                                .padding(horizontal = 16.dp),
                            colors = CardDefaults.cardColors(containerColor = colors.primaryContainer.copy(alpha = 0.3f)),
                            elevation = CardDefaults.cardElevation(defaultElevation = 0.dp)
                        ) {
                            Row(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .padding(12.dp),
                                verticalAlignment = Alignment.CenterVertically,
                                horizontalArrangement = Arrangement.SpaceBetween
                            ) {
                                Text("Stay hydrated — drink water!", style = typography.bodyMedium, color = colors.onPrimaryContainer)
                                TextButton(onClick = { /* could open hydration scheduling */ }) { Text("Tips") }
                            }
                        }
                    }
                }
            }
        }
    }
    
    // Auto-generate meal plan dialog
    if (showAutoGenerateDialog) {
        AutoGenerateMealPlanSheet(
            onDismiss = { showAutoGenerateDialog = false },
            onGenerate = { calories, dietType, allergies ->
                viewModel.generateMealPlan(calories, dietType, allergies)
                showAutoGenerateDialog = false
            }
        )
    }
    
    // Add custom meal bottom sheet
    if (showAddMealDialog) {
        AddCustomMealBottomSheet(
            selectedDay = selectedDateValue.dayOfWeek,
            onDismiss = { showAddMealDialog = false },
            onAdd = { time, name, description, calories ->
                val meal = MealPlanItem(
                    id = "${selectedDateValue.dayOfWeek}_${time.name}_${System.currentTimeMillis()}",
                    name = when(time) { MealTime.Breakfast -> "Breakfast"; MealTime.Lunch -> "Lunch"; MealTime.Dinner -> "Dinner"; MealTime.Snacks -> "Snacks" },
                    calories = calories,
                    day = selectedDateValue.dayOfWeek,
                    time = time,
                    description = description.ifEmpty { name },
                    recipeId = null,
                    imageUrl = null
                )
                viewModel.addMeal(meal)
                showAddMealDialog = false
            }
        )
    }
    
    // Nutrition summary dialog
    if (showNutritionDialog) {
        NutritionSummaryDialog(
            dailyNutrition = dailyNutrition,
            selectedDate = selectedDateValue,
            onDismiss = { showNutritionDialog = false }
        )
    }
    
    // Share dialog removed
}

@Composable
fun CalendarView(
    dates: List<LocalDate>,
    selectedDate: LocalDate,
    onDateSelected: (LocalDate) -> Unit
) {
    val colors = MaterialTheme.colorScheme
    val typography = MaterialTheme.typography
    
    Column(
        modifier = Modifier
            .fillMaxWidth()
            .padding(16.dp)
    ) {
        // Month and year header
        Text(
            text = selectedDate.format(DateTimeFormatter.ofPattern("MMMM yyyy")),
            style = typography.titleMedium.copy(fontWeight = FontWeight.Bold),
            color = colors.onBackground
        )
        
        Spacer(modifier = Modifier.height(16.dp))
        
        // Days of week
        LazyRow(
            horizontalArrangement = Arrangement.spacedBy(8.dp),
            contentPadding = PaddingValues(vertical = 8.dp)
        ) {
            items(dates) { date ->
                DateItem(
                    date = date,
                    isSelected = date == selectedDate,
                    onDateSelected = onDateSelected
                )
            }
        }
        
        HorizontalDivider(
            color = colors.surfaceVariant,
            modifier = Modifier.padding(vertical = 16.dp)
        )
    }
}

@Composable
fun DateItem(
    date: LocalDate,
    isSelected: Boolean,
    onDateSelected: (LocalDate) -> Unit
) {
    val colors = MaterialTheme.colorScheme
    val typography = MaterialTheme.typography
    
    val today = LocalDate.now()
    val isToday = date.equals(today)
    
    val backgroundColor = when {
        isSelected -> colors.primary
        isToday -> colors.primaryContainer
        else -> colors.surface
    }
    
    val textColor = when {
        isSelected -> colors.onPrimary
        isToday -> colors.onPrimaryContainer
        else -> colors.onSurface
    }
    
    Column(
        horizontalAlignment = Alignment.CenterHorizontally,
        modifier = Modifier
            .width(45.dp)
            .clip(RoundedCornerShape(12.dp))
            .clickable { onDateSelected(date) }
            .background(backgroundColor)
            .padding(vertical = 8.dp, horizontal = 4.dp)
    ) {
        // Day of week (e.g., Mon)
        Text(
            text = date.dayOfWeek.getDisplayName(TextStyle.SHORT, Locale.getDefault()),
            style = typography.bodySmall,
            color = textColor
        )
        
        Spacer(modifier = Modifier.height(4.dp))
        
        // Day of month (e.g., 15)
        Text(
            text = date.dayOfMonth.toString(),
            style = typography.titleMedium.copy(fontWeight = FontWeight.Bold),
            color = textColor
        )
    }
}

@Composable
fun DailyMealPlan(
    date: LocalDate,
    meals: List<MealPlanItem>,
    onDeleteMeal: (MealPlanItem) -> Unit,
    onAddMeal: (mealTime: String, name: String, description: String, calories: Int, recipeId: String?) -> Unit,
    colors: ColorScheme,
    typography: Typography,
    onRecipeClick: (String?) -> Unit,
    onUpdateMeal: (MealPlanItem) -> Unit,
    onShowAddSheet: () -> Unit
) {
    val mealTimes = listOf("Breakfast", "Lunch", "Dinner", "Snacks")
    
    Column(
        modifier = Modifier
            .fillMaxWidth()
            .padding(horizontal = 16.dp)
    ) {
        Text(
            text = "Meals for ${date.format(DateTimeFormatter.ofPattern("EEEE, MMMM d"))}",
            style = typography.titleMedium.copy(fontWeight = FontWeight.Medium),
            color = colors.onBackground
        )
        
        Spacer(modifier = Modifier.height(16.dp))
        
        LazyColumn(
            verticalArrangement = Arrangement.spacedBy(16.dp),
            modifier = Modifier.fillMaxWidth()
        ) {
            items(mealTimes) { mealTime ->
                val mealForTime = meals.firstOrNull { it.time.name == mealTime }
                android.util.Log.d("MealPlannerScreen", "Looking for $mealTime, found: ${mealForTime?.name ?: "none"}")
                
                MealTimeCard(
                    mealTime = mealTime,
                    meal = mealForTime,
                    onDeleteMeal = onDeleteMeal,
                    onAddMeal = onAddMeal,
                    colors = colors,
                    typography = typography,
                    onRecipeClick = onRecipeClick,
                    onUpdateMeal = onUpdateMeal,
                    onShowAddSheet = onShowAddSheet
                )
            }
            
            item {
                Spacer(modifier = Modifier.height(80.dp)) // Space for FAB
            }
        }
    }
}

@Composable
fun MealTimeCard(
    mealTime: String,
    meal: MealPlanItem?,
    onDeleteMeal: (MealPlanItem) -> Unit,
    onAddMeal: (mealTime: String, name: String, description: String, calories: Int, recipeId: String?) -> Unit,
    colors: ColorScheme,
    typography: Typography,
    onRecipeClick: (String?) -> Unit,
    onUpdateMeal: (MealPlanItem) -> Unit,
    onShowAddSheet: () -> Unit
) {
    val mealTimeIcon = when(mealTime) {
        "Breakfast" -> Icons.Default.FreeBreakfast
        "Lunch" -> Icons.Default.LunchDining
        "Dinner" -> Icons.Default.DinnerDining
        else -> Icons.Default.Restaurant
    }
    
    var showAddMealDialog by remember { mutableStateOf(false) }
    
    // Swipe to edit/delete for manual meals
    @OptIn(ExperimentalMaterial3Api::class)
    val canSwipe = meal != null
    if (canSwipe && meal != null) {
        var showEdit by remember { mutableStateOf(false) }
        val dismissState = androidx.compose.material3.rememberSwipeToDismissBoxState(confirmValueChange = { value ->
            when (value) {
                androidx.compose.material3.SwipeToDismissBoxValue.EndToStart -> {
                    onDeleteMeal(meal)
                    true
                }
                androidx.compose.material3.SwipeToDismissBoxValue.StartToEnd -> {
                    showEdit = true
                    false
                }
                else -> false
            }
        })
        androidx.compose.material3.SwipeToDismissBox(
            state = dismissState,
            backgroundContent = {},
            enableDismissFromStartToEnd = true,
            enableDismissFromEndToStart = true
        ) {
            MealCardContent(mealTime, meal, onDeleteMeal, onAddMeal, colors, typography, onRecipeClick, onUpdateMeal, onShowAddSheet)
        }
        if (showEdit) {
            EditMealBottomSheet(meal = meal, colors = colors, typography = typography, onDismiss = { showEdit = false }) { updated ->
                onUpdateMeal(updated)
                showEdit = false
            }
        }
    } else {
        MealCardContent(mealTime, meal, onDeleteMeal, onAddMeal, colors, typography, onRecipeClick, onUpdateMeal, onShowAddSheet)
    }
}

@Composable
private fun MealCardContent(
    mealTime: String,
    meal: MealPlanItem?,
    onDeleteMeal: (MealPlanItem) -> Unit,
    onAddMeal: (mealTime: String, name: String, description: String, calories: Int, recipeId: String?) -> Unit,
    colors: ColorScheme,
    typography: Typography,
    onRecipeClick: (String?) -> Unit,
    onUpdateMeal: (MealPlanItem) -> Unit,
    onShowAddSheet: () -> Unit
) {
    Card(
        modifier = Modifier.fillMaxWidth(),
        colors = CardDefaults.cardColors(
            containerColor = colors.surface
        ),
        elevation = CardDefaults.cardElevation(defaultElevation = 0.dp)
    ) {
        Column(
            modifier = Modifier.fillMaxWidth()
        ) {
            // If we have an image, show it
            meal?.imageUrl?.let { imageUrl ->
                if (imageUrl.isNotEmpty()) {
                    AsyncImage(
                        model = imageUrl,
                        contentDescription = meal.description,
                        contentScale = ContentScale.Crop,
                        modifier = Modifier
                            .fillMaxWidth()
                            .height(120.dp)
                    )
                }
            }
            
            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(16.dp),
                verticalAlignment = Alignment.CenterVertically
            ) {
                // Meal time icon
                Box(
                    modifier = Modifier
                        .size(48.dp)
                        .clip(RoundedCornerShape(12.dp))
                        .background(colors.primaryContainer),
                    contentAlignment = Alignment.Center
                ) {
                    val icon = when(mealTime) {
                        "Breakfast" -> Icons.Default.FreeBreakfast
                        "Lunch" -> Icons.Default.LunchDining
                        "Dinner" -> Icons.Default.DinnerDining
                        else -> Icons.Default.Restaurant
                    }
                    Icon(
                        imageVector = icon,
                        contentDescription = mealTime,
                        tint = colors.onPrimaryContainer,
                        modifier = Modifier.size(24.dp)
                    )
                }
                
                Spacer(modifier = Modifier.width(16.dp))
                
                // Meal info
                Column(
                    modifier = Modifier.weight(1f)
                ) {
                    Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                        Text(
                            text = mealTime,
                            style = typography.titleMedium.copy(fontWeight = FontWeight.Medium),
                            color = colors.onSurface
                        )
                        if (meal != null && meal.recipeId == null) {
                            Text("added by me", style = typography.labelSmall, color = colors.primary)
                        }
                    }
                    
                    if (meal != null) {
                        Spacer(modifier = Modifier.height(4.dp))
                        Text(
                            text = meal.description ?: meal.name,
                            style = typography.bodyMedium,
                            color = colors.onSurface.copy(alpha = 0.8f)
                        )
                        Spacer(modifier = Modifier.height(2.dp))
                        Text(
                            text = "${meal.calories} kcal",
                            style = typography.bodySmall,
                            color = colors.onSurface.copy(alpha = 0.6f)
                        )
                    } else {
                        Spacer(modifier = Modifier.height(4.dp))
                        Text(
                            text = "No meal planned",
                            style = typography.bodyMedium,
                            color = colors.onSurface.copy(alpha = 0.6f)
                        )
                    }
                }
                
                // Actions
                Row {
                    if (meal?.recipeId != null) {
                        IconButton(onClick = { onRecipeClick(meal.recipeId) }) {
                            Icon(
                                imageVector = Icons.Default.Restaurant,
                                contentDescription = "View recipe",
                                tint = colors.primary
                            )
                        }
                    }
                    
                    if (meal != null) {
                        if (meal.recipeId == null) {
                            // manual meal: show edit
                            var showEdit by remember { mutableStateOf(false) }
                            IconButton(onClick = { showEdit = true }) {
                                Icon(imageVector = Icons.Default.Edit, contentDescription = "Edit", tint = colors.primary)
                            }
                            if (showEdit) {
                                EditMealBottomSheet(meal = meal, colors = colors, typography = typography, onDismiss = { showEdit = false }) { updated ->
                                    onUpdateMeal(updated)
                                    showEdit = false
                                }
                            }
                        }
                        IconButton(onClick = { onDeleteMeal(meal) }) {
                            Icon(
                                imageVector = Icons.Default.Delete,
                                contentDescription = "Delete meal",
                                tint = colors.error.copy(alpha = 0.7f)
                            )
                        }
                    } else {
                        TextButton(
                            onClick = onShowAddSheet,
                            colors = ButtonDefaults.textButtonColors(
                                contentColor = colors.primary
                            )
                        ) {
                            Text("Add")
                        }
                    }
                }
            }
        }
    }
    
}

@Composable
@OptIn(androidx.compose.material3.ExperimentalMaterial3Api::class)
fun AutoGenerateMealPlanSheet(
    onDismiss: () -> Unit,
    onGenerate: (calories: Int, dietType: String, allergies: List<String>) -> Unit
) {
    val colors = MaterialTheme.colorScheme
    val typography = MaterialTheme.typography

    // Preferences
    var targetCalories by remember { mutableStateOf(2000) }
    var selectedDietType by remember { mutableStateOf("Balanced") }
    val dietTypes = listOf("Balanced", "Low-carb", "High-protein", "Vegetarian", "Vegan")
    var showAdvancedOptions by remember { mutableStateOf(false) }
    
    // Allergies/restrictions
    var glutenFree by remember { mutableStateOf(false) }
    var nutFree by remember { mutableStateOf(false) }
    
    androidx.compose.material3.ModalBottomSheet(
        onDismissRequest = onDismiss,
        dragHandle = { androidx.compose.material3.BottomSheetDefaults.DragHandle() }
    ) {
        Column(
            modifier = Modifier
                .fillMaxWidth()
                .padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            Text(
                text = "Auto-generate Meal Plan",
                style = typography.titleLarge.copy(fontWeight = FontWeight.Bold)
            )
            Text(
                text = "Let us create a personalized meal plan based on your preferences.",
                style = typography.bodyMedium,
                color = colors.onSurface.copy(alpha = 0.8f)
            )
            Text(
                text = "Daily calories: $targetCalories",
                style = typography.bodyMedium.copy(fontWeight = FontWeight.Medium)
            )
            Slider(
                value = targetCalories.toFloat(),
                onValueChange = { targetCalories = it.toInt() },
                valueRange = 1200f..3500f,
                steps = 23,
                colors = SliderDefaults.colors(
                    thumbColor = colors.primary,
                    activeTrackColor = colors.primary
                )
            )
            Text(
                text = "Diet type",
                style = typography.bodyMedium.copy(fontWeight = FontWeight.Medium)
            )
            LazyRow(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                items(dietTypes) { dietType ->
                    val isSelected = dietType == selectedDietType
                    FilterChip(
                        selected = isSelected,
                        onClick = { selectedDietType = dietType },
                        label = { Text(dietType) },
                        colors = FilterChipDefaults.filterChipColors(
                            selectedContainerColor = colors.primaryContainer,
                            selectedLabelColor = colors.onPrimaryContainer
                        )
                    )
                }
            }
            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .clickable { showAdvancedOptions = !showAdvancedOptions },
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.SpaceBetween
            ) {
                Text(
                    text = "Advanced options",
                    style = typography.bodyMedium.copy(fontWeight = FontWeight.Medium)
                )
                Icon(
                    imageVector = if (showAdvancedOptions) Icons.Default.ExpandLess else Icons.Default.ExpandMore,
                    contentDescription = if (showAdvancedOptions) "Hide advanced options" else "Show advanced options"
                )
            }
            AnimatedVisibility(visible = showAdvancedOptions) {
                Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                    Text(text = "Food allergies/restrictions", style = typography.bodySmall)
                    Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                        FilterChip(selected = glutenFree, onClick = { glutenFree = !glutenFree }, label = { Text("Gluten-free") })
                        FilterChip(selected = nutFree, onClick = { nutFree = !nutFree }, label = { Text("Nut-free") })
                    }
                }
            }
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                OutlinedButton(
                    onClick = onDismiss,
                    modifier = Modifier.weight(1f)
                ) { Text("Cancel") }
                Button(
                    onClick = {
                        val allergies = mutableListOf<String>().apply {
                            if (glutenFree) add("gluten")
                            if (nutFree) add("nuts")
                        }
                        onGenerate(targetCalories, selectedDietType, allergies)
                    },
                    modifier = Modifier.weight(1f),
                    colors = ButtonDefaults.buttonColors(containerColor = colors.primary)
                ) { Text("Generate") }
            }
        }
    }
}

@Composable
fun AddCustomMealDialog(
    mealTime: String,
    onDismiss: () -> Unit,
    onAddMeal: (name: String, description: String, calories: Int, recipeId: String?) -> Unit
) {
    val colors = MaterialTheme.colorScheme
    val typography = MaterialTheme.typography
    
    var mealName by remember { mutableStateOf("") }
    var mealDescription by remember { mutableStateOf("") }
    var caloriesText by remember { mutableStateOf("") }
    var recipeIdText by remember { mutableStateOf("") }
    
    val isAddEnabled = mealName.isNotEmpty() && caloriesText.isNotEmpty()
            
    AlertDialog(
        onDismissRequest = onDismiss,
        title = {
            Text(
                text = "Add $mealTime",
                style = typography.titleLarge.copy(fontWeight = FontWeight.Bold)
            )
        },
        text = {
            Column(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(vertical = 8.dp),
                verticalArrangement = Arrangement.spacedBy(16.dp)
            ) {
                OutlinedTextField(
                    value = mealName,
                    onValueChange = { mealName = it },
                    label = { Text("Meal Name") },
                    singleLine = true,
                    modifier = Modifier.fillMaxWidth()
                )
                
                OutlinedTextField(
                    value = mealDescription,
                    onValueChange = { mealDescription = it },
                    label = { Text("Description (optional)") },
                    modifier = Modifier.fillMaxWidth()
                )
                
                OutlinedTextField(
                    value = caloriesText,
                    onValueChange = { 
                        // Only allow numbers
                        if (it.isEmpty() || it.all { char -> char.isDigit() }) {
                            caloriesText = it
                        }
                    },
                    label = { Text("Calories") },
                    keyboardOptions = KeyboardOptions(
                        keyboardType = KeyboardType.Number
                    ),
                    singleLine = true,
                    modifier = Modifier.fillMaxWidth()
                )
                
                OutlinedTextField(
                    value = recipeIdText,
                    onValueChange = { recipeIdText = it },
                    label = { Text("Recipe ID (optional)") },
                    singleLine = true,
                    modifier = Modifier.fillMaxWidth()
                )
            }
        },
        confirmButton = {
            Button(
                onClick = {
                    val calories = caloriesText.toIntOrNull() ?: 0
                    val recipeId = if (recipeIdText.isBlank()) null else recipeIdText
                    onAddMeal(mealName, mealDescription, calories, recipeId)
                },
                enabled = isAddEnabled,
                colors = ButtonDefaults.buttonColors(
                    containerColor = colors.primary
                )
            ) {
                Text("Add Meal")
            }
        },
        dismissButton = {
            TextButton(onClick = onDismiss) {
                Text("Cancel")
            }
        }
    )
}

@Composable
fun AddCustomMealTimeDialog(
    onDismiss: () -> Unit,
    onSelectMealTime: (mealTime: String, name: String, description: String, calories: Int, recipeId: String?) -> Unit
) {
    val colors = MaterialTheme.colorScheme
    val typography = MaterialTheme.typography
    
    val mealTimes = listOf("Breakfast", "Lunch", "Dinner", "Snacks")
    var selectedMealTime by remember { mutableStateOf(mealTimes[0]) }
    
    var mealName by remember { mutableStateOf("") }
    var mealDescription by remember { mutableStateOf("") }
    var caloriesText by remember { mutableStateOf("") }
    var recipeIdText by remember { mutableStateOf("") }
    
    val isAddEnabled = mealName.isNotEmpty() && caloriesText.isNotEmpty()
    
    AlertDialog(
        onDismissRequest = onDismiss,
        title = {
            Text(
                text = "Add Custom Meal",
                style = typography.titleLarge.copy(fontWeight = FontWeight.Bold)
            )
        },
        text = {
            Column(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(vertical = 8.dp),
                verticalArrangement = Arrangement.spacedBy(16.dp)
            ) {
                // Meal time selection
                Text(
                    text = "Meal Time",
                    style = typography.bodyMedium.copy(fontWeight = FontWeight.Medium)
                )
                LazyRow(
                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                ) {
                    items(mealTimes) { mealTime ->
                        val isSelected = mealTime == selectedMealTime
                        FilterChip(
                            selected = isSelected,
                            onClick = { selectedMealTime = mealTime },
                            label = { Text(mealTime) },
                            colors = FilterChipDefaults.filterChipColors(
                                selectedContainerColor = colors.primaryContainer,
                                selectedLabelColor = colors.onPrimaryContainer
                            )
                        )
                    }
                }
                
                // Meal details
                OutlinedTextField(
                    value = mealName,
                    onValueChange = { mealName = it },
                    label = { Text("Meal Name") },
                    singleLine = true,
                    modifier = Modifier.fillMaxWidth()
                )
                
                OutlinedTextField(
                    value = mealDescription,
                    onValueChange = { mealDescription = it },
                    label = { Text("Description (optional)") },
                    modifier = Modifier.fillMaxWidth()
                )
                
                OutlinedTextField(
                    value = caloriesText,
                    onValueChange = { 
                        // Only allow numbers
                        if (it.isEmpty() || it.all { char -> char.isDigit() }) {
                            caloriesText = it
                        }
                    },
                    label = { Text("Calories") },
                    keyboardOptions = KeyboardOptions(
                        keyboardType = KeyboardType.Number
                    ),
                    singleLine = true,
                    modifier = Modifier.fillMaxWidth()
                )
                
                OutlinedTextField(
                    value = recipeIdText,
                    onValueChange = { recipeIdText = it },
                    label = { Text("Recipe ID (optional)") },
                    singleLine = true,
                    modifier = Modifier.fillMaxWidth()
                )
            }
        },
        confirmButton = {
            Button(
                onClick = {
                    val calories = caloriesText.toIntOrNull() ?: 0
                    val recipeId = if (recipeIdText.isBlank()) null else recipeIdText
                    onSelectMealTime(selectedMealTime, mealName, mealDescription, calories, recipeId)
                },
                enabled = isAddEnabled,
                colors = ButtonDefaults.buttonColors(
                    containerColor = colors.primary
                )
            ) {
                Text("Add Meal")
            }
        },
        dismissButton = {
            TextButton(onClick = onDismiss) {
                Text("Cancel")
            }
        }
    )
}

@Composable
@OptIn(androidx.compose.material3.ExperimentalMaterial3Api::class)
fun NutritionSummaryDialog(
    dailyNutrition: Map<DayOfWeek, NutritionSummary>,
    selectedDate: LocalDate,
    onDismiss: () -> Unit
) {
    val colors = MaterialTheme.colorScheme
    val typography = MaterialTheme.typography

    val selectedDayNutrition = dailyNutrition[selectedDate.dayOfWeek]

    androidx.compose.material3.ModalBottomSheet(
        onDismissRequest = onDismiss,
        dragHandle = { androidx.compose.material3.BottomSheetDefaults.DragHandle() }
    ) {
        Column(
            modifier = Modifier
                .fillMaxWidth()
                .padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            Text(
                text = "Nutrition Summary",
                style = typography.titleLarge.copy(fontWeight = FontWeight.Bold)
            )

            Text(
                text = "Daily Nutrition for ${selectedDate.format(DateTimeFormatter.ofPattern("EEEE, MMMM d"))}",
                style = typography.bodyMedium,
                color = colors.onSurface
            )

            if (selectedDayNutrition != null) {
                // Interactive macro bar chart
                MacroBarChart(
                    values = listOf(
                        Triple("Protein", selectedDayNutrition.protein.toFloat(), Color(0xFF4CAF50)),
                        Triple("Carbs", selectedDayNutrition.carbs.toFloat(), Color(0xFFFFC107)),
                        Triple("Fat", selectedDayNutrition.fat.toFloat(), Color(0xFFE91E63))
                    ),
                    colors = colors,
                    typography = typography
                )
                // Interactive macro pie chart
                MacroPieChart(
                    protein = selectedDayNutrition.protein.toFloat(),
                    carbs = selectedDayNutrition.carbs.toFloat(),
                    fat = selectedDayNutrition.fat.toFloat()
                )
            } else {
                Text(
                    text = "No meals planned for this day.",
                    style = typography.bodyMedium,
                    color = colors.onSurface.copy(alpha = 0.6f),
                    textAlign = TextAlign.Center,
                    modifier = Modifier.fillMaxWidth()
                )
            }

            Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.End) {
                TextButton(onClick = onDismiss) { Text("Close") }
            }
        }
    }
}

@Composable
fun NutritionProgressBar(
    label: String,
    value: Int,
    maxValue: Int,
    colors: ColorScheme,
    typography: Typography,
    valueLabel: String,
    progressColor: Color = colors.primary
) {
    val progress = (value.toFloat() / maxValue).coerceIn(0f, 1f)
    Column(modifier = Modifier.fillMaxWidth()) {
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically
        ) {
            Text(text = label, style = typography.bodyMedium)
            Text(text = valueLabel, style = typography.bodySmall)
        }
        Spacer(modifier = Modifier.height(4.dp))
        LinearProgressIndicator(
            progress = { progress },
            modifier = Modifier
                .fillMaxWidth()
                .height(8.dp)
                .clip(RoundedCornerShape(4.dp)),
            color = progressColor,
            trackColor = colors.surfaceVariant
        )
    }
} 

@Composable
private fun MacroBarChart(
    values: List<Triple<String, Float, Color>>,
    colors: ColorScheme,
    typography: Typography
) {
    var selectedIndex by remember { mutableStateOf<Int?>(null) }
    val maxVal = (values.maxOfOrNull { it.second } ?: 1f).coerceAtLeast(1f)
    Column(modifier = Modifier.fillMaxWidth()) {
        androidx.compose.foundation.Canvas(
            modifier = Modifier
                .fillMaxWidth()
                .height(120.dp)
                .clip(RoundedCornerShape(12.dp))
                .background(colors.surfaceVariant)
        ) {
            val barWidth = size.width / (values.size * 2f)
            val gap = barWidth
            var x = gap / 2f
            values.forEachIndexed { idx, (_, v, c) ->
                val h = (v / maxVal) * size.height * 0.9f
                val top = size.height - h
                drawRect(
                    color = if (selectedIndex == idx) c.copy(alpha = 0.9f) else c.copy(alpha = 0.7f),
                    topLeft = androidx.compose.ui.geometry.Offset(x, top),
                    size = androidx.compose.ui.geometry.Size(barWidth, h)
                )
                x += barWidth + gap
            }
        }
        Spacer(modifier = Modifier.height(8.dp))
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.SpaceEvenly,
            verticalAlignment = Alignment.CenterVertically
        ) {
            values.forEachIndexed { idx, (label, v, c) ->
                Column(horizontalAlignment = Alignment.CenterHorizontally) {
                    Box(
                        modifier = Modifier
                            .size(10.dp)
                            .clip(CircleShape)
                            .background(c)
                    )
                    Text(
                        text = if (selectedIndex == idx) "$label: ${v.toInt()}g" else label,
                        style = typography.bodySmall,
                        color = colors.onSurface
                    )
                }
            }
        }
    }
}

@Composable
private fun MacroPieChart(
    protein: Float,
    carbs: Float,
    fat: Float
) {
    val total = (protein + carbs + fat).coerceAtLeast(1f)
    val segments = listOf(
        Triple("Protein", protein / total, Color(0xFF4CAF50)),
        Triple("Carbs", carbs / total, Color(0xFFFFC107)),
        Triple("Fat", fat / total, Color(0xFFE91E63))
    )
    var selected by remember { mutableStateOf<Int?>(null) }

    Box(modifier = Modifier.fillMaxWidth(), contentAlignment = Alignment.Center) {
        androidx.compose.foundation.Canvas(
            modifier = Modifier
                .size(180.dp)
        ) {
            var startAngle = -90f
            val radius = size.minDimension / 2f
            segments.forEachIndexed { idx, seg ->
                val sweep = seg.second * 360f
                val isSel = selected == idx
                val r = if (isSel) radius * 1.06f else radius
                drawArc(
                    color = seg.third,
                    startAngle = startAngle,
                    sweepAngle = sweep,
                    useCenter = true,
                    topLeft = androidx.compose.ui.geometry.Offset(
                        (size.width / 2f) - r,
                        (size.height / 2f) - r
                    ),
                    size = androidx.compose.ui.geometry.Size(r * 2, r * 2)
                )
                startAngle += sweep
            }
        }
        selected?.let { idx ->
            val label = segments[idx].first
            val pct = (segments[idx].second * 100f).toInt()
            Column(horizontalAlignment = Alignment.CenterHorizontally) {
                Text(text = label, fontWeight = FontWeight.Bold)
                Text(text = "$pct%")
            }
        }
    }
} 

// Logged meals UI removed

// Scanner helpers removed 

@OptIn(ExperimentalMaterial3Api::class)
@Composable
private fun AddCustomMealBottomSheet(
    selectedDay: DayOfWeek,
    onDismiss: () -> Unit,
    onAdd: (MealTime, String, String, Int) -> Unit
) {
    val colors = MaterialTheme.colorScheme
    val typography = MaterialTheme.typography
    var selectedTime by remember { mutableStateOf(MealTime.Breakfast) }
    var name by remember { mutableStateOf("") }
    var description by remember { mutableStateOf("") }
    var caloriesText by remember { mutableStateOf("") }
    androidx.compose.material3.ModalBottomSheet(onDismissRequest = onDismiss, dragHandle = { androidx.compose.material3.BottomSheetDefaults.DragHandle() }) {
        Column(modifier = Modifier.fillMaxWidth().padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {
            Text("Add custom meal", style = typography.titleLarge.copy(fontWeight = FontWeight.Bold))
            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                listOf(MealTime.Breakfast, MealTime.Lunch, MealTime.Dinner, MealTime.Snacks).forEach { t ->
                    FilterChip(selected = selectedTime == t, onClick = { selectedTime = t }, label = { Text(t.name) })
                }
            }
            OutlinedTextField(value = name, onValueChange = { name = it }, label = { Text("Meal name") }, singleLine = true, modifier = Modifier.fillMaxWidth())
            OutlinedTextField(value = description, onValueChange = { description = it }, label = { Text("Description (optional)") }, modifier = Modifier.fillMaxWidth())
            OutlinedTextField(value = caloriesText, onValueChange = { if (it.all { c -> c.isDigit() } || it.isEmpty()) caloriesText = it }, label = { Text("Calories") }, singleLine = true, modifier = Modifier.fillMaxWidth())
            Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                TextButton(onClick = onDismiss, modifier = Modifier.weight(1f)) { Text("Cancel") }
                Button(onClick = {
                    val cal = caloriesText.toIntOrNull() ?: 0
                    onAdd(selectedTime, name, description, cal)
                }, enabled = name.isNotBlank() && (caloriesText.toIntOrNull() ?: 0) > 0, modifier = Modifier.weight(1f)) { Text("Add") }
            }
        }
    }
} 

@OptIn(ExperimentalMaterial3Api::class)
@Composable
private fun EditMealBottomSheet(
    meal: MealPlanItem,
    colors: ColorScheme,
    typography: Typography,
    onDismiss: () -> Unit,
    onSave: (MealPlanItem) -> Unit
) {
    var name by remember { mutableStateOf(meal.description ?: meal.name) }
    var description by remember { mutableStateOf(meal.description ?: "") }
    var caloriesText by remember { mutableStateOf(meal.calories.toString()) }
    var time by remember { mutableStateOf(meal.time) }
    androidx.compose.material3.ModalBottomSheet(onDismissRequest = onDismiss, dragHandle = { androidx.compose.material3.BottomSheetDefaults.DragHandle() }) {
        Column(modifier = Modifier.fillMaxWidth().padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {
            Text("Edit meal", style = typography.titleLarge.copy(fontWeight = FontWeight.Bold))
            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                listOf(MealTime.Breakfast, MealTime.Lunch, MealTime.Dinner, MealTime.Snacks).forEach { t ->
                    FilterChip(selected = time == t, onClick = { time = t }, label = { Text(t.name) })
                }
            }
            OutlinedTextField(value = name, onValueChange = { name = it }, label = { Text("Meal name") }, singleLine = true, modifier = Modifier.fillMaxWidth())
            OutlinedTextField(value = description, onValueChange = { description = it }, label = { Text("Description (optional)") }, modifier = Modifier.fillMaxWidth())
            OutlinedTextField(value = caloriesText, onValueChange = { if (it.all { c -> c.isDigit() } || it.isEmpty()) caloriesText = it }, label = { Text("Calories") }, singleLine = true, modifier = Modifier.fillMaxWidth())
            Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                TextButton(onClick = onDismiss, modifier = Modifier.weight(1f)) { Text("Cancel") }
                Button(onClick = {
                    val updated = meal.copy(
                        name = when(time){ MealTime.Breakfast->"Breakfast"; MealTime.Lunch->"Lunch"; MealTime.Dinner->"Dinner"; MealTime.Snacks->"Snacks" },
                        time = time,
                        description = description.ifEmpty { name },
                        calories = caloriesText.toIntOrNull() ?: meal.calories
                    )
                    onSave(updated)
                }, enabled = name.isNotBlank() && (caloriesText.toIntOrNull() ?: 0) > 0, modifier = Modifier.weight(1f)) { Text("Save") }
            }
        }
    }
} 